### ISSUE TITLE
使用主题的时候, 主题文件报错

### ISSUE THREAD

**Issue by liaohui1080** [liekkas/re-echarts#3]
dark.js 

3:41  error  'define' is not defined  no-undef
  5:9   error  'define' is not defined  no-undef

**Comment by liekkas** [comment]
你是怎么使用主题的？

**Comment by liaohui1080** [comment]
主题导入的时候后报错的, 
主题似乎不支持 es6 这样的语法,
把顶部 判断 导入的那块删了, 就可以了
